-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-03-22 16:20:46 EDT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE assignment (
    billing_rate        NUMBER,
    employees_emp_id    VARCHAR2(4000) NOT NULL,
    projects_project_id VARCHAR2(4000) NOT NULL,
    start_date          DATE NOT NULL,
    end_date            DATE
);

ALTER TABLE assignment
    ADD CONSTRAINT assignment_pk PRIMARY KEY ( employees_emp_id,
                                               projects_project_id,
                                               start_date );

CREATE TABLE component_counts (
    components_component_no  VARCHAR2(4000) NOT NULL,
    components_component_no1 VARCHAR2(4000) NOT NULL,
    component_count          INTEGER
);

ALTER TABLE component_counts ADD CONSTRAINT relation_5_pk PRIMARY KEY ( components_component_no,
                                                                        components_component_no1 );

CREATE TABLE components (
    component_no    VARCHAR2(4000) NOT NULL,
    description     VARCHAR2(4000),
    unit_of_measure NUMBER
);

ALTER TABLE components ADD CONSTRAINT components_pk PRIMARY KEY ( component_no );

CREATE TABLE employees (
    emp_id    VARCHAR2(4000) NOT NULL,
    name      VARCHAR2(4000),
    address   VARCHAR2(4000),
    birthdate DATE
);

ALTER TABLE employees ADD CONSTRAINT employees_pk PRIMARY KEY ( emp_id );

CREATE TABLE product_component_count (
    products_product_no     VARCHAR2(4000) NOT NULL,
    components_component_no VARCHAR2(4000) NOT NULL,
    component_count         INTEGER NOT NULL
);

ALTER TABLE product_component_count ADD CONSTRAINT relation_4_pk PRIMARY KEY ( products_product_no,
                                                                               components_component_no );

CREATE TABLE products (
    product_no          VARCHAR2(4000) NOT NULL,
    description         VARCHAR2(4000),
    cost                NUMBER,
    projects_project_id VARCHAR2(4000) NOT NULL
);

ALTER TABLE products ADD CONSTRAINT products_pk PRIMARY KEY ( product_no );

CREATE TABLE projects (
    project_id   VARCHAR2(4000) NOT NULL,
    project_name VARCHAR2(4000),
    start_date   DATE
);

ALTER TABLE projects ADD CONSTRAINT projects_pk PRIMARY KEY ( project_id );

ALTER TABLE assignment
    ADD CONSTRAINT assignment_employees_fk FOREIGN KEY ( employees_emp_id )
        REFERENCES employees ( emp_id );

ALTER TABLE assignment
    ADD CONSTRAINT assignment_projects_fk FOREIGN KEY ( projects_project_id )
        REFERENCES projects ( project_id );

ALTER TABLE products
    ADD CONSTRAINT products_projects_fk FOREIGN KEY ( projects_project_id )
        REFERENCES projects ( project_id );

ALTER TABLE product_component_count
    ADD CONSTRAINT relation_4_components_fk FOREIGN KEY ( components_component_no )
        REFERENCES components ( component_no );

ALTER TABLE product_component_count
    ADD CONSTRAINT relation_4_products_fk FOREIGN KEY ( products_product_no )
        REFERENCES products ( product_no );

ALTER TABLE component_counts
    ADD CONSTRAINT relation_5_components_fk FOREIGN KEY ( components_component_no )
        REFERENCES components ( component_no );

ALTER TABLE component_counts
    ADD CONSTRAINT relation_5_components_fkv1 FOREIGN KEY ( components_component_no1 )
        REFERENCES components ( component_no );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             14
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
