-- Question 1 --
SELECT
    HR_EMPLOYEES.FIRST_NAME,
    HR_EMPLOYEES.LAST_NAME,
    HR_EMPLOYEES.HIRE_DATE,
    NVL(HR_EMPLOYEES.COMMISSION_PCT, 0)
FROM
    HR_EMPLOYEES
ORDER BY
    LAST_NAME;

-- Question 2a
SELECT
    FIRST_NAME,
    LAST_NAME,
    HIRE_DATE,
    NVL(HR_EMPLOYEES.COMMISSION_PCT, 0)
FROM
    HR_EMPLOYEES
WHERE
    EMPLOYEE_ID > 150;

-- Question 2b
SELECT
    FIRST_NAME,
    LAST_NAME,
    HIRE_DATE,
    NVL(HR_EMPLOYEES.COMMISSION_PCT, 0)
FROM
    HR_EMPLOYEES
WHERE
    FIRST_NAME LIKE 'D%'
ORDER BY
    LAST_NAME;

-- Question 2c --
SELECT
    FIRST_NAME,
    LAST_NAME,
    HIRE_DATE,
    NVL(HR_EMPLOYEES.COMMISSION_PCT, 0)
FROM
    HR_EMPLOYEES
WHERE
    FIRST_NAME LIKE '%D%'
    OR FIRST_NAME LIKE '%d%'
ORDER BY
    LAST_NAME;

-- Question 2d --
SELECT
    FIRST_NAME,
    LAST_NAME,
    HIRE_DATE,
    NVL(HR_EMPLOYEES.COMMISSION_PCT, 0)
FROM
    HR_EMPLOYEES
WHERE
    LAST_NAME > 'Matos'
ORDER BY
    LAST_NAME;

-- Question 2e --
SELECT
    FIRST_NAME,
    LAST_NAME,
    HIRE_DATE,
    NVL(HR_EMPLOYEES.COMMISSION_PCT, 0)
FROM
    HR_EMPLOYEES
WHERE
    HIRE_DATE > '01-MAR-06'
ORDER BY
    LAST_NAME;

-- Question 2f --
SELECT
    FIRST_NAME,
    LAST_NAME,
    HIRE_DATE,
    NVL(HR_EMPLOYEES.COMMISSION_PCT, 0)
FROM
    HR_EMPLOYEES
WHERE
    SALARY BETWEEN 10000 AND 12000
ORDER BY
    LAST_NAME;

-- Question 2g --
SELECT
    FIRST_NAME,
    LAST_NAME,
    HIRE_DATE,
    NVL(HR_EMPLOYEES.COMMISSION_PCT, 0)
FROM
    HR_EMPLOYEES
WHERE
    JOB_ID ='FI_ACCOUNT'
    OR JOB_ID = 'SA_MAN'
ORDER BY
    LAST_NAME;

-- Question 2h --
SELECT
    FIRST_NAME,
    LAST_NAME,
    HIRE_DATE,
    PHONE_NUMBER,
    NVL(HR_EMPLOYEES.COMMISSION_PCT, 0)
FROM
    HR_EMPLOYEES
WHERE
    SUBSTR(PHONE_NUMBER, 1, 3) = '515'
ORDER BY
    LAST_NAME;

-- Question 2i --
SELECT
    FIRST_NAME,
    LAST_NAME,
    HIRE_DATE,
    NVL(HR_EMPLOYEES.COMMISSION_PCT, 0)
FROM
    HR_EMPLOYEES
WHERE
    DEPARTMENT_ID IS NULL
ORDER BY
    LAST_NAME;

-- Question 3 --
SELECT
    AVG(SALARY)
FROM
    HR_EMPLOYEES;

-- Question 4 --
SELECT
    FIRST_NAME,
    LAST_NAME,
    SALARY,
    ROUND(SALARY * 03.8398, 2) AS ROUNDED_CITY_TAX
FROM
    HR_EMPLOYEES
ORDER BY
    ROUNDED_CITY_TAX DESC;

-- Question 5 --
SELECT
    COUNT(DEPARTMENT_ID)       AS TOTAL_DEPARTMENTS,
    COUNT(*)-COUNT(MANAGER_ID) AS TOTAL_DEPARTMENTS_WITHOUT_MANAGERS
FROM
    HR_DEPARTMENTS;

-- Question 6 --
SELECT
    EMPLOYEE_ID,
    JOB_ID,
    TO_CHAR(START_DATE, 'yyyy') AS FROM_YEAR,
    TO_CHAR(END_DATE, 'yyyy')   AS TO_YEAR
FROM
    HR_JOB_HISTORY;

-- Question 7 --
SELECT
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME
FROM
    HR_EMPLOYEES
WHERE
    MANAGER_ID IS NULL
    AND COMMISSION_PCT IS NULL;

-- Question 8 --
SELECT
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME
FROM
    HR_EMPLOYEES
WHERE
    MANAGER_ID IS NULL
    OR COMMISSION_PCT IS NULL;

-- Question 9a --
SELECT
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    JOB_ID,
    SALARY
FROM
    HR_EMPLOYEES
WHERE
    JOB_ID LIKE 'IT_PROG'
    AND SALARY >=8000
    OR JOB_ID LIKE 'FI_ACCOUNT';

-- Question 9b --
SELECT
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    JOB_ID,
    SALARY
FROM
    HR_EMPLOYEES
WHERE
    JOB_ID LIKE 'IT_PROG'
    AND SALARY >=8000
    OR JOB_ID LIKE'FI_ACCOUNT'
    AND SALARY >= 8000;

-- Question 10a --
SELECT
    MANAGER_ID,
    JOB_ID,
    SALARY
FROM
    HR_EMPLOYEES
ORDER BY
    MANAGER_ID,
    SALARY;

-- Question 10b --
SELECT
    MANAGER_ID,
    JOB_ID,
    SALARY
FROM
    HR_EMPLOYEES
ORDER BY
    MANAGER_ID,
    SALARY DESC;

-- Question 10c --
SELECT
    MANAGER_ID,
    JOB_ID,
    SALARY
FROM
    HR_EMPLOYEES
ORDER BY
    MANAGER_ID DESC,
    SALARY DESC;

-- Question 11a --
SELECT
    COUNT(LOCATION_ID)
FROM
    HR_LOCATIONS;

-- Question 11b --
SELECT
    COUNTRY_ID,
    COUNT(LOCATION_ID)
FROM
    HR_LOCATIONS
GROUP BY
    COUNTRY_ID;

-- Question 12 --
SELECT
    COUNTRY_ID,
    LOCATION_ID
FROM
    HR_LOCATIONS;

WHERE
COUNT(LOCATION_ID) >= 2;

-- Question 13 --
SELECT
    DEPARTMENT_ID,
    COUNT(EMPLOYEE_ID) AS EMPLOYEE_COUNT
FROM
    HR_EMPLOYEES
GROUP BY
    DEPARTMENT_ID
ORDER BY
    EMPLOYEE_COUNT DESC;

-- Question 14a --
SELECT
    TO_CHAR(HIRE_DATE, 'yyyy'),
    COUNT(EMPLOYEE_ID)
FROM
    HR_EMPLOYEES
GROUP BY
    TO_CHAR(HIRE_DATE, 'yyyy');

-- Question 14b --
SELECT
    TO_CHAR(HIRE_DATE, 'yyyy'),
    COUNT(EMPLOYEE_ID)
FROM
    HR_EMPLOYEES
WHERE
    EXTRACT(MONTH FROM HIRE_DATE) = 3
GROUP BY
    TO_CHAR(HIRE_DATE, 'yyyy');

-- Question 14c --
SELECT
    TO_CHAR(HIRE_DATE, 'yyyy'),
    COUNT(EMPLOYEE_ID)
FROM
    HR_EMPLOYEES
WHERE
    EXTRACT(YEAR FROM HIRE_DATE) >= 2006
GROUP BY
    TO_CHAR(HIRE_DATE, 'yyyy');

-- Question 14d --
SELECT
    TO_CHAR(HIRE_DATE, 'yyyy'),
    COUNT(EMPLOYEE_ID)
FROM
    HR_EMPLOYEES
GROUP BY
    TO_CHAR(HIRE_DATE, 'yyyy')
HAVING
    COUNT(EMPLOYEE_ID) > 2;

-- Question 14e --
SELECT
    DEPARTMENT_ID,
    TO_CHAR(HIRE_DATE, 'yyyy'),
    COUNT(EMPLOYEE_ID)
FROM
    HR_EMPLOYEES
GROUP BY
    DEPARTMENT_ID,
    TO_CHAR(HIRE_DATE, 'yyyy');