-- Question 1 --
SELECT
    HR_EMPLOYEES.FIRST_NAME,
    HR_EMPLOYEES.LAST_NAME,
    HR_EMPLOYEES.HIRE_DATE,
    NVL(HR_EMPLOYEES.COMMISSION_PCT, 0)
FROM
    HR_EMPLOYEES
ORDER BY
    LAST_NAME;

-- Question 2a
SELECT
    FIRST_NAME,
    LAST_NAME,
    HIRE_DATE,
    NVL(HR_EMPLOYEES.COMMISSION_PCT, 0)
FROM
    HR_EMPLOYEES
WHERE
    EMPLOYEE_ID > 150;

-- Question 2b
SELECT
    FIRST_NAME,
    LAST_NAME,
    HIRE_DATE,
    NVL(HR_EMPLOYEES.COMMISSION_PCT, 0)
FROM
    HR_EMPLOYEES
WHERE
    FIRST_NAME LIKE 'D%'
ORDER BY
    LAST_NAME;

-- Question 2c --
SELECT
    FIRST_NAME,
    LAST_NAME,
    HIRE_DATE,
    NVL(HR_EMPLOYEES.COMMISSION_PCT, 0)
FROM
    HR_EMPLOYEES
WHERE
    FIRST_NAME LIKE '%D%'
    OR FIRST_NAME LIKE '%d%'
ORDER BY
    LAST_NAME;

-- Question 2d --
SELECT
    FIRST_NAME,
    LAST_NAME,
    HIRE_DATE,
    NVL(HR_EMPLOYEES.COMMISSION_PCT, 0)
FROM
    HR_EMPLOYEES
WHERE
    LAST_NAME > 'Matos'
ORDER BY
    LAST_NAME;

-- Question 2e --
SELECT
    FIRST_NAME,
    LAST_NAME,
    HIRE_DATE,
    NVL(HR_EMPLOYEES.COMMISSION_PCT, 0)
FROM
    HR_EMPLOYEES
WHERE
    HIRE_DATE > '01-MAR-06'
ORDER BY
    LAST_NAME;

-- Question 2f --
SELECT
    FIRST_NAME,
    LAST_NAME,
    HIRE_DATE,
    NVL(HR_EMPLOYEES.COMMISSION_PCT, 0)
FROM
    HR_EMPLOYEES
WHERE
    SALARY BETWEEN 10000 AND 12000
ORDER BY
    LAST_NAME;

-- Question 2g --
SELECT
    FIRST_NAME,
    LAST_NAME,
    HIRE_DATE,
    NVL(HR_EMPLOYEES.COMMISSION_PCT, 0)
FROM
    HR_EMPLOYEES
WHERE
    JOB_ID ='FI_ACCOUNT'
    OR JOB_ID = 'SA_MAN'
ORDER BY
    LAST_NAME;

-- Question 2h --
SELECT
    FIRST_NAME,
    LAST_NAME,
    HIRE_DATE,
    PHONE_NUMBER,
    NVL(HR_EMPLOYEES.COMMISSION_PCT, 0)
FROM
    HR_EMPLOYEES
WHERE
    SUBSTR(PHONE_NUMBER, 1, 3) = '515'
ORDER BY
    LAST_NAME;

-- Question 2i --
SELECT
    FIRST_NAME,
    LAST_NAME,
    HIRE_DATE,
    NVL(HR_EMPLOYEES.COMMISSION_PCT, 0)
FROM
    HR_EMPLOYEES
WHERE
    DEPARTMENT_ID IS NULL
ORDER BY
    LAST_NAME;

-- Question 3 --
SELECT
    AVG(SALARY)
FROM
    HR_EMPLOYEES;

-- Question 4 --
SELECT
    FIRST_NAME,
    LAST_NAME,
    SALARY,
    ROUND(SALARY * 03.8398, 2) AS ROUNDED_CITY_TAX
FROM
    HR_EMPLOYEES
ORDER BY
    ROUNDED_CITY_TAX DESC;

-- Question 5 --
SELECT
    COUNT(DEPARTMENT_ID)       AS TOTAL_DEPARTMENTS,
    COUNT(*)-COUNT(MANAGER_ID) AS TOTAL_DEPARTMENTS_WITHOUT_MANAGERS
FROM
    HR_DEPARTMENTS;

-- Question 6 --
SELECT
    EMPLOYEE_ID,
    JOB_ID,
    TO_CHAR(START_DATE, 'yyyy') AS FROM_YEAR,
    TO_CHAR(END_DATE, 'yyyy')   AS TO_YEAR
FROM
    HR_JOB_HISTORY
-- Question 7 --