--- Question 1a ---
SELECT
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME
FROM
    HR_EMPLOYEES;

--- Question 1a ---
CREATE OR REPLACE FUNCTION HIGH_SALARY(
    HIGH_SALARY_ID IN NUMBER
) RETURN NUMBER IS
    COUNTS NUMBER(11, 2);
BEGIN
    SELECT
        COUNT(*) INTO COUNTS
    FROM
        HR_EMPLOYEES
    WHERE
        SALARY > (
            SELECT
                SALARY
            FROM
                HR_EMPLOYEES
            WHERE
                EMPLOYEE_ID=HIGH_SALARY_ID
        );
    RETURN(COUNTS);
END;
 --- Question1b1 ---
SELECT
    HIGH_SALARY(103)
FROM
    DUAL;
 --- Question1b2 ---
SELECT
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    SALARY,
    HIGH_SALARY(EMPLOYEE_ID)
FROM
    HR_EMPLOYEES;
 --- Question 2A ---
CREATE OR REPLACE PROCEDURE SALARY_INCREASE(JID IN VARCHAR2) IS
BEGIN
    UPDATE HR_EMPLOYEES
    SET
        SALARY = SALARY + 10000
    WHERE
        JOB_ID = JID;
END;
 --- Question 2B ---
DROP TRIGGER SECURE_HR_EMPLOYEES;
DROP TRIGGER UPDATE_HR_JOB_HISTORY;
EXECUTE SALARY_INCREASE('IT_PROG');
 --- Question 2C ---
ROLLBACK;
 --- Question 3A ---
CREATE OR REPLACE VIEW IT_EMPLOYEES AS
    SELECT   (FIRST_NAME
              || ' '
              || LAST_NAME) AS NAME, JOB_ID, SALARY FROM HR_EMPLOYEES WHERE(HR_EMPLOYEES.JOB_ID='IT_PROG');
 --- Question 3B ---
    UPDATE   IT_EMPLOYEES SET SALARY = 60000;
    ROLLBACK;
    SELECT   * FROM IT_EMPLOYEES;
    SELECT   * FROM HR_EMPLOYEES;
 --- Question 3C ---
    CREATE   OR REPLACE VIEW IT_EMPLOYEES_HIGH AS
    SELECT
        (FIRST_NAME
         || ' '
         || LAST_NAME) AS NAME,
        JOB_ID,
        SALARY
    FROM
        HR_EMPLOYEES
    WHERE
        (HR_EMPLOYEES.JOB_ID='IT_PROG'
        AND SALARY > 5000)WITH CHECK OPTION;
    SELECT   * FROM IT_EMPLOYEES_HIGH;
    SELECT   * FROM HR_EMPLOYEES;
    UPDATE   HR_EMPLOYEES SET SALARY = 4000;